spring:
  data:
    redis:
      repositories:
        enabled: false

datasource:
  redis:
    database: 0
    master:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
    replicas:
      - host: ${REDIS_REPLICA_1_HOST}
        port: ${REDIS_REPLICA_1_PORT}

---
spring.config.activate.on-profile: local, test

datasource:
  redis:
    master:
      host: localhost
      port: 6379
      timeout: 3000                 # 명령 실행 제한 시간
    replicas:
      - host: localhost
        port: 6380

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd
